modLoader = "javafml"
loaderVersion = "[43,)"
license = "Apache-2.0"

[[mods]]
modId = "nears"
version = "${file.jarVersion}"
displayName = "Nears"
authors = "LimonBlaze"
credits = "Thanks DigitalPear, IssysArt and Omaypaty for the original work"
description = '''
Fauna of the nether.
'''

[[dependencies.nears]]
modId = "forge"
mandatory = true
versionRange = "[43.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nears]]
modId= "minecraft"
mandatory= true
versionRange= "[1.19.2,1.19.3)"
ordering= "NONE"
side= "BOTH"